[theme]
primaryColor="#FF4B4B" # A vibrant red for buttons/highlights
backgroundColor="#FFFFFF" # White background
secondaryBackgroundColor="#F0F2F6" # Light grey for secondary elements
textColor="#262730" # Dark grey for text
font="sans serif"


